config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :municipes

  root to: 'municipes#index'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :municipe

  validates :city, :public_place, :neighborhood, :uf, :cep, presence: true

  UFS = [
    'AC',
    'AL',
    'AP',
    'AM',
    'BA',
    'CE',
    'DF',
    'ES',
    'GO',
    'MA',
    'MT',
    'MS',
    'MG',
    'PA',
    'PB',
    'PR',
    'PE',
    'PI',
    'RJ',
    'RN',
    'RS',
    'RO',
    'RR',
    'SC',
    'SP',
    'SE',
    'TO'
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  max_pages 25

	validates :birth_date, :cns, :email, :cpf, :full_name, :telephone, presence: true
  validate :cpf_valid?
  validate :is_email_valid?, :validate_age
  validate :cns_valid?

  has_one :address, :dependent => :destroy
  has_one_attached :image

  validates_associated :address
  accepts_nested_attributes_for :address

  scope :filter_by_cpf, -> (cpf) { where('cpf like :search', search: cpf) }

  def validate_age
    if birth_date.present? && birth_date.strftime('%Y') > 18.years.ago.strftime('%Y')
      return I18n.t('activerecord.errors.messages.birth_date_invalid')
    end
  end

  def cpf_valid?
    invalid_cpf_values = CPF_INVALID_DIGITS

    cpf_digit = self.cpf.scan /[0-9]/

    if cpf_digit.length == 11
      unless invalid_cpf_values.member?(cpf_digit.join)
        cpf_digit = cpf_digit.collect{|x| x.to_i}

        cpf_sum = 10*cpf_digit[0]+9*cpf_digit[1]+8*cpf_digit[2]+7*cpf_digit[3]+6*cpf_digit[4]+5*cpf_digit[5]+4*cpf_digit[6]+3*cpf_digit[7]+2*cpf_digit[8]
        cpf_sum = cpf_sum - (11 * (cpf_sum/11))
        cpf_sum_result = (cpf_sum == 0 or cpf_sum == 1) ? 0 : 11 - cpf_sum

        if cpf_sum_result == cpf_digit[9]
          cpf_sum = cpf_digit[0]*11+cpf_digit[1]*10+cpf_digit[2]*9+cpf_digit[3]*8+cpf_digit[4]*7+cpf_digit[5]*6+cpf_digit[6]*5+cpf_digit[7]*4+cpf_digit[8]*3+cpf_digit[9]*2
          cpf_sum = cpf_sum - (11 * (cpf_sum/11))
          cpf_sum_result_last_digit = (cpf_sum == 0 or cpf_sum == 1) ? 0 : 11 - cpf_sum

          self.cpf.gsub!(/[^\d]/, '')

          return true if cpf_sum_result_last_digit == cpf_digit[10]

        end
      end
    end

    return message_error_cpf
  end

  def cns_valid?

    if cns.present?
      cns = self.cns.gsub!(/\s+/, '')

      return cns_incomplete if cns.length != 15
      return message_error_cns unless cns.match?(/\A\d+\Z/)

      case cns.chars.first
        when '1', '2'
          cns_validation_return = valid_cns(cns)
        when '7', '8', '9'
          cns_validation_return = validate_provisional_cns(cns)
        else
          return message_error_cns
      end

      return message_error_cns if cns_validation_return == false
    end
  end

  def is_email_valid?
    self.email =~ FORMAT_CHARACTER_EMAIL
  end

  private

  CPF_INVALID_DIGITS = %w{
    12345678909
    11111111111
    22222222222
    33333333333
    44444444444
    55555555555
    66666666666
    77777777777
    88888888888
    99999999999
    00000000000
    12345678909
  }

  FORMAT_CHARACTER_EMAIL = /^(.+)@(.+)$/


  def valid_cns(cns)
    pis = cns[0..11]

    sum = pis.chars.each_with_index.inject(0) do |result, (char, i)|
      result += char.to_i * (15 - i)
      result
    end

    dv = 11 - (sum % 11)
    dv = dv == 11 ? 0 : dv
    cns_generated =
      if dv == 10
        sum += 2
        dv = 11 - (sum % 11)
        "#{pis}001#{dv}"
      else
        "#{pis}00#{dv}"
      end
    puts "total da soma #{dv}"
    return cns == cns_generated
  end

  def validate_provisional_cns(cns)
    sum =
      cns.chars.each_with_index.inject(0) do |result, (char, i)|
        result += char.to_i * (15 - i)
        result
      end

    return (sum % 11) == 0
  end

  def message_error_cns
    errors.add(:cns, message: I18n.t("cns_is_not_invalid"))
  end

  def cns_incomplete
    errors.add(:cns, message: I18n.t("cns_incomplete"))
  end

  def message_error_cpf
    errors.add(:cpf, message: I18n.t("cpf_is_not_invalid"))
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index;  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end


    private

    def address_params
      params.require(:address).permit(:id, :cep, :public_place, :complement, :neighborhood, :city, :uf, :ibge_code, :municipe_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update ]

  def index
    @municipe = Municipe.all
    @municipe = @municipe.filter_by_cpf(params[:search_municipe][:cpf]) if params[:search_municipe]

    paginate
  end

  def new
    @municipe = Municipe.new
    @municipe.build_address
  end

  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save

        MunicipeMailer.with(user: @municipe).welcome_email.deliver_now!
        SendSms.new(@municipe).call

        format.html { redirect_to municipe_url(@municipe), notice: t('notice.registration_created_successfully') }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @municipe.update(municipe_params)

        MunicipeMailer.with(user: @municipe).welcome_email.deliver_now!
        SendSms.new(@municipe).call

        format.html { redirect_to municipe_url(@municipe), notice: t('notice.registration_updated_successfully') }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def paginate
    @municipe = Municipe.limit(5)
    @municipe.page(1).per(20).size
    @municipe.page(1).per(20).total_count
  end

  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  def municipe_params
    params.require(:municipe).permit(
      :full_name, :cpf, :cns, :email, :birth_date, :telephone, :image,
      :status, { address_attributes: [:cep, :public_place, :complement, :neighborhood, :city, :uf,
      :ibge_code] }
    )
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: @address, local: true) do |f| %>
  <div class="row">
    <div class="col-4">
      <%= f.label :cep, class: 'text-secondary m-1' %>
      <%= f.text_field :cep, id: 'cep', class: 'form-control', onkeypress:"$(this).mask('00000-000')" %>
    </div>
    <div class="col-4">
      <%= f.label I18n.t('address.public_place'), class: 'text-secondary m-1' %>
      <%= f.text_field :public_place, id: 'public_place', class: 'form-control' %>
    </div>
    <div class="col-4">
      <%= f.label I18n.t('address.complement'), class: 'text-secondary m-1' %>
      <%= f.text_field :complement, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <%= f.label I18n.t('address.neighborhood'), class: 'text-secondary m-1' %>
      <%= f.text_field :neighborhood, id: 'neighborhood', class: 'form-control' %>
    </div>
    <div class="col-3">
      <%= f.label I18n.t('address.city'), class: 'text-secondary m-1' %>
      <%= f.text_field :city, id: 'city', class: 'form-control' %>
    </div>
    <div class="col-3">
      <%= f.label :uf, class: 'text-secondary m-1' %>
      <%= f.select :uf, options_for_select(Address::UFS.map {|uf| uf}), {include_blank: true}, class: 'form-control form-control-multiple' %>
    </div>
    <div class="col-3">
      <%= f.label I18n.t('address.ibge_code'), class: 'text-secondary m-1' %>
      <%= f.text_field :ibge_code, id: 'ibge_code' , class: 'form-control' %>
    </div>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Cep</th>
      <th>Public place</th>
      <th>Complement</th>
      <th>Neighborhood</th>
      <th>City</th>
      <th>Uf</th>
      <th>Ibge code</th>
      <th>Municipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.cep %></td>
        <td><%= address.public_place %></td>
        <td><%= address.complement %></td>
        <td><%= address.neighborhood %></td>
        <td><%= address.city %></td>
        <td><%= address.uf %></td>
        <td><%= address.ibge_code %></td>
        <td><%= address.municipe %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cep:</strong>
  <%= @address.cep %>
</p>

<p>
  <strong>Public place:</strong>
  <%= @address.public_place %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @address.complement %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @address.neighborhood %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @address.uf %>
</p>

<p>
  <strong>Ibge code:</strong>
  <%= @address.ibge_code %>
</p>

<p>
  <strong>Municipe:</strong>
  <%= @address.municipe %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/component/_form_action.html.erb
<div class="row">
  <div class="col-1">
    <%= link_to I18n.t('back'), url_for(controller: controller_name, action: 'index'), class: "btn btn-dark btn-primary" %>
  </div>

  <div class="col-1">
    <%= (local_assigns[:form] || form).button :submit, t('create'), class: "btn btn-primary btn-dark" %>
  </div>
</div>

app/views/component/_simples_form_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="form-error alert alert-error">
    <%= t('errors.template.body') %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'postoffice' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= simple_form_for @municipe do |form| %>
  <%= render 'component/simples_form_errors', object: form.object %>

  <hr>

  <div class="row">
    <div class="col-3">
      <%= form.label I18n.t('municipe.full_name'), class: 'text-secondary m-1' %>
      <%= form.text_field :full_name, class: "form-control" %>
    </div>
    <div class="col-3">
      <%= form.label :cpf, class: 'text-secondary m-1' %>
      <%= form.text_field :cpf, id: 'cpf', class: "form-control cpf" %>
    </div>
    <div class="col-3">
      <%= form.label I18n.t("municipe.cns"), class: 'text-secondary m-1' %>
      <%= form.text_field :cns, class: "form-control cns", required: true %>
    </div>
    <div class="col-3">
      <%= form.label :email, class: 'text-secondary m-1' %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 mb-3">
        <label class="text-secondary m-1"><%= t('municipe.birth_date') %></label>
        <div class="input-group w-100">
          <%= form.input :birth_date, as: :date, html5: true, label: false %>
        </div>
      </div>
    <div class="col-4">
      <%= form.label I18n.t('municipe.telephone'), class: 'text-secondary m-1' %>
      <%= form.text_field :telephone, class: "form-control tel" %>
    </div>
    <div class="col-4">
      <div class="form-check form-switch mt-4">
        <%= form.label :status, class: "form-check-label text-secondary" %>
        <%= form.check_box :status, { class: "form-check-input"}, "true", "false" %>
      </div>
    </div>
  </div>
  <div class='w-25 file-input'>
      <%= form.input :image,  as: :file, label: false %>
  </div>

  <hr />

  <fieldset>
    <%= form.fields_for :address do |f| %>
      <%= render 'form_address', f: f %>
    <% end %>
  </fieldset>

  <br>

  <%= render 'component/form_action', form: form %>
<% end %>

app/views/municipes/_form_address.html.erb
<div class="row">
  <div class="col-4">
    <%= f.label :cep, class: 'text-secondary m-1' %>
    <%= f.text_field :cep, id: 'cep', class: 'form-control cep' %>
  </div>
  <div class="col-4">
    <%= f.label I18n.t('address.public_place'), class: 'text-secondary m-1' %>
    <%= f.text_field :public_place, id: 'public_place', class: 'form-control' %>
  </div>
  <div class="col-4">
    <%= f.label I18n.t('address.complement'), class: 'text-secondary m-1' %>
    <%= f.text_field :complement, class: 'form-control' %>
  </div>
</div>

<div class="row">
  <div class="col-3">
    <%= f.label I18n.t('address.neighborhood'), class: 'text-secondary m-1' %>
    <%= f.text_field :neighborhood, id: 'neighborhood', class: 'form-control' %>
  </div>
  <div class="col-3">
    <%= f.label I18n.t('address.city'), class: 'text-secondary m-1' %>
    <%= f.text_field :city, id: 'city', class: 'form-control' %>
  </div>
  <div class="col-3">
    <%= f.label :uf, class: 'text-secondary m-1' %>
    <%= f.select :uf, options_for_select(Address::UFS.map {|uf| uf}), {include_blank: true}, class: 'form-control form-control-multiple' %>
  </div>
  <div class="col-3">
    <%= f.label I18n.t('address.ibge_code'), class: 'text-secondary m-1' %>
    <%= f.text_field :ibge_code, id: 'ibge_code' , class: 'form-control' %>
  </div>
</div>

app/views/municipes/_search.html.erb
<%= simple_form_for :search_municipe, method: "GET",  id: 'search_municipes', html: { data: {turbo: false}} do |f| %>
  <div class='row'>
    <div class='col-3'>
      <%= f.label :cpf %>
      <%= f.text_field :cpf, class: 'form-control mb-2', label: false %>
    </div>
    <div class='col-3 mt-4'>
      <%= f.submit t('search'), class: 'btn btn-outline-dark' %>
    </div>
  </div>
<% end %>

app/views/municipes/edit.html.erb
<h1><%= I18n.t('municipe.editing_municipe') %></h1>

<%= render 'form', municipe: @municipe %>

<%#= link_to I18n.t('show'), @municipe %> |
<%#= link_to I18n.t('back'), municipes_path %>

app/views/municipes/index.html.erb
<p id="alert alert-success text-success"><%= notice %></p>

<%= render 'search' %>

<br>

<h1><%= t('activerecord.municipe') %></h1>

<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('municipe.full_name') %></th>
      <th><%= t('municipe.cpf') %></th>
      <th><%= t('municipe.cns') %></th>
      <th><%= t('municipe.email') %></th>
      <th><%= t('municipe.birth_date') %></th>
      <th><%= t('municipe.telephone') %></th>
      <th>Status</th>
      <th><%= t('action') %></th>
    </tr>
  </thead>

  <tbody>
    <% @municipe.each do |municipe| %>
      <tr>
        <td><%= municipe.full_name %></td>
        <td class='cpf'><%= municipe.cpf %></td>
        <td class='cns'><%= municipe.cns %></td>
        <td><%= municipe.email %></td>
        <td><%= municipe.birth_date.strftime('%d/%m/%Y') %></td>
        <td class='tel'><%= municipe.telephone %></td>
        <td><%= t(municipe.status, scope: 'municipe.status') %></td>
        <td>
          <%= link_to municipe,  class: 'text-success size-icon' do %>
            <i class="fa-regular fa-eye"></i>
          <% end %>

          <%= link_to edit_municipe_path(municipe), class: 'text-info size-icon' do %>
            <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('municipe.new_municipe'), new_municipe_path, class: 'btn btn-dark mb-3' %>

app/views/municipes/new.html.erb
<h1><%= I18n.t('municipe.new_municipe') %></h1>

<%= render 'form', municipe: @municipe %>

<%#= link_to I18n.t('back'), municipes_path %>

app/views/municipes/show.html.erb
<p class="text-success mt-2"><%= notice %></p>

<div class='row'>
  <div class='col-md-12'>
    <div class='card'>
      <div class='card-header'>
        <h4 class="card-title">
            <%= t('activerecord.municipe') %>
        </h4>
      </div>
      <div class='card-body'>
        <div class='row'>
          <div class='col-5 form-group'>
              <strong><%= I18n.t('municipe.full_name') %></strong>
              <input value='<%= @municipe.full_name %>', class='form-control', disabled />
          </div>
          <div class='col-3'>
            <strong>Cpf:</strong>
            <input value='<%= @municipe.cpf %>', class='form-control cpf', disabled />
          </div>
          <div class='col-4'>
            <strong>Cns:</strong>
            <input value='<%= @municipe.cns %>', class='form-control cns', disabled />
          </div>
        </div>
        <div class='row mt-3'>
          <div class='col-3'>
            <strong>Email:</strong>
            <input value='<%= @municipe.email %>', class='form-control', disabled />
          </div>
          <div class='col-3'>
            <strong><%= I18n.t('municipe.birth_date') %></strong>
            <input value='<%= @municipe.birth_date.strftime('%d/%m/%Y') %>', class='form-control', disabled />
          </div>
          <div class='col-3'>
            <strong><%= I18n.t('municipe.telephone') %></strong>
            <input value='<%= @municipe.telephone %>', class='form-control tel', disabled />
          </div>
          <div class='col-3'>
            <strong>Status:</strong>
            <input value='<%= t(@municipe.status, scope: "municipe.status") %>', class='form-control', disabled />
          </div>
        </div>
        <div class='mt-3'>
          <div class='col-6'>
            <% if @municipe.image.attached? %>
              <%= image_tag @municipe.image, width: 200, heigth: 200 %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<div class='row'>
  <div class='col-md-12'>
    <div class='card'>
      <div class='card-header'>
        <h4 class="card-title">
          <%= t('activerecord.address') %>
        </h4>
      </div>
      <div class='card-body'>
        <div class='row'>
          <div class='col-4'>
              <strong><%= I18n.t('address.cep') %></strong>
              <input value='<%= @municipe.address.cep %>', class='form-control cep', disabled />
          </div>
          <div class='col-4'>
            <strong><%= I18n.t('address.neighborhood') %></strong>
            <input value='<%= @municipe.address.neighborhood %>', class='form-control', disabled />
          </div>
          <div class='col-4'>
            <strong><%= I18n.t('address.public_place') %></strong>
            <input value='<%= @municipe.address.public_place %>', class='form-control', disabled />
          </div>
        </div>
        <div class='row mt-3'>
          <div class='col-3'>
            <strong><%= I18n.t('address.complement') %></strong>
            <input value='<%= @municipe.address.complement %>', class='form-control', disabled />
          </div>
          <div class='col-3'>
            <strong><%= I18n.t('address.city') %></strong>
            <input value='<%= @municipe.address.city %>', class='form-control', disabled />
          </div>
          <div class='col-3'>
            <strong><%= I18n.t('address.uf') %></strong>
            <input value='<%= @municipe.address.uf %>', class='form-control', disabled />
          </div>
          <div class='col-3'>
            <strong><%= I18n.t('address.ibge_code') %></strong>
            <input value='<%= @municipe.address.ibge_code %>', class='form-control', disabled />
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class='mb-3 d-flex justify-content-between'>
  <%= link_to municipes_path, class: 'text-dark size-icon' do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>

  <%= link_to edit_municipe_path(@municipe), class:'text-success size-icon' do %>
    <i class="fa-regular fa-pen-to-square"></i>
  <% end %>
</div>